name: CI

on:
  push:
    branches:
      - main
      - deploy-ci

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: BUILDKIT_INLINE_CACHE=1
          tags: ${{ secrets.DOCKER_REGISTRY }}/user_lz/mocked-sensors-main:latest
